// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NYSE.API.Models;

namespace NYSE.API.Migrations
{
    [DbContext(typeof(DailyPriceContext))]
    [Migration("20190723061756_NYSE_initialMigration")]
    partial class NYSE_initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NYSE.API.Model.DailyPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("date");

                    b.Property<string>("stock_exchange")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<decimal>("stock_price_adj_close")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("stock_price_close")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("stock_price_high")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("stock_price_low")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("stock_price_open")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("stock_symbol")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<int>("stock_volume");

                    b.HasKey("Id");

                    b.ToTable("DailyPrice");
                });
#pragma warning restore 612, 618
        }
    }
}
